# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt22_brower.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(739, 424)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pbDatabaseCteate = QtWidgets.QPushButton(Form)
        self.pbDatabaseCteate.setObjectName("pbDatabaseCteate")
        self.verticalLayout_2.addWidget(self.pbDatabaseCteate)
        self.pbConnData = QtWidgets.QPushButton(Form)
        self.pbConnData.setObjectName("pbConnData")
        self.verticalLayout_2.addWidget(self.pbConnData)
        self.pbTableCreate = QtWidgets.QPushButton(Form)
        self.pbTableCreate.setObjectName("pbTableCreate")
        self.verticalLayout_2.addWidget(self.pbTableCreate)
        self.pbValueInsert = QtWidgets.QPushButton(Form)
        self.pbValueInsert.setObjectName("pbValueInsert")
        self.verticalLayout_2.addWidget(self.pbValueInsert)
        self.pbValueDelete = QtWidgets.QPushButton(Form)
        self.pbValueDelete.setObjectName("pbValueDelete")
        self.verticalLayout_2.addWidget(self.pbValueDelete)
        self.pbTableDelete = QtWidgets.QPushButton(Form)
        self.pbTableDelete.setObjectName("pbTableDelete")
        self.verticalLayout_2.addWidget(self.pbTableDelete)
        self.pbDisConnData = QtWidgets.QPushButton(Form)
        self.pbDisConnData.setObjectName("pbDisConnData")
        self.verticalLayout_2.addWidget(self.pbDisConnData)
        self.pbExit = QtWidgets.QPushButton(Form)
        self.pbExit.setObjectName("pbExit")
        self.verticalLayout_2.addWidget(self.pbExit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb1 = QtWidgets.QLabel(Form)
        self.lb1.setObjectName("lb1")
        self.horizontalLayout_2.addWidget(self.lb1)
        self.lb2 = QtWidgets.QLabel(Form)
        self.lb2.setObjectName("lb2")
        self.horizontalLayout_2.addWidget(self.lb2)
        self.lb3 = QtWidgets.QLabel(Form)
        self.lb3.setObjectName("lb3")
        self.horizontalLayout_2.addWidget(self.lb3)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.pbConnData.clicked.connect(Form.conn_data)
        self.pbDisConnData.clicked.connect(Form.dis_conn_data)
        self.pbExit.clicked.connect(Form.close)
        self.pbTableCreate.clicked.connect(Form.table_create)
        self.pbTableDelete.clicked.connect(Form.table_delete)
        self.pbValueInsert.clicked.connect(Form.value_insert)
        self.pbValueDelete.clicked.connect(Form.value_delete)
        self.pbDatabaseCteate.clicked.connect(Form.database_create)
        self.listWidget.doubleClicked['QModelIndex'].connect(Form.list_double_click)
        self.listWidget.currentTextChanged['QString'].connect(Form.list_text_changed)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "数据库操作(SQLite)"))
        self.pbDatabaseCteate.setText(_translate("Form", "新建数据库"))
        self.pbConnData.setText(_translate("Form", "连接数据库"))
        self.pbTableCreate.setText(_translate("Form", "新建一个表"))
        self.pbValueInsert.setText(_translate("Form", "插入一条记录"))
        self.pbValueDelete.setText(_translate("Form", "删除一条记录"))
        self.pbTableDelete.setText(_translate("Form", "删除一个表"))
        self.pbDisConnData.setText(_translate("Form", "断开数据库"))
        self.pbExit.setText(_translate("Form", "退出"))
        self.lb1.setText(_translate("Form", "数据库："))
        self.lb2.setText(_translate("Form", "表："))
        self.lb3.setText(_translate("Form", "记录："))

