# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt23_listWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1130, 600)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 256, 381))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(280, 10, 160, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_start = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_start.setObjectName("pb_start")
        self.verticalLayout.addWidget(self.pb_start)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 33))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pb_add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_add.setObjectName("pb_add")
        self.verticalLayout.addWidget(self.pb_add)
        self.pb_del = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_del.setObjectName("pb_del")
        self.verticalLayout.addWidget(self.pb_del)
        self.pb_clear_all = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_clear_all.setObjectName("pb_clear_all")
        self.verticalLayout.addWidget(self.pb_clear_all)
        self.pb_info = QtWidgets.QPushButton(self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.pb_info.setPalette(palette)
        self.pb_info.setObjectName("pb_info")
        self.verticalLayout.addWidget(self.pb_info)
        self.pb_exit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_exit.setObjectName("pb_exit")
        self.verticalLayout.addWidget(self.pb_exit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tb_r = QtWidgets.QTextBrowser(Form)
        self.tb_r.setGeometry(QtCore.QRect(460, 30, 651, 81))
        self.tb_r.setObjectName("tb_r")
        self.tb_info = QtWidgets.QTextBrowser(Form)
        self.tb_info.setGeometry(QtCore.QRect(460, 410, 651, 181))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.tb_info.setPalette(palette)
        self.tb_info.setObjectName("tb_info")
        self.tb_run = QtWidgets.QTextBrowser(Form)
        self.tb_run.setGeometry(QtCore.QRect(460, 290, 651, 101))
        self.tb_run.setObjectName("tb_run")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(460, 10, 391, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(460, 270, 401, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(460, 120, 481, 16))
        self.label_3.setObjectName("label_3")
        self.tb_item_clicked = QtWidgets.QTextBrowser(Form)
        self.tb_item_clicked.setGeometry(QtCore.QRect(460, 140, 651, 121))
        self.tb_item_clicked.setObjectName("tb_item_clicked")

        self.retranslateUi(Form)
        self.pb_add.clicked.connect(Form.add)
        self.pb_del.clicked.connect(Form.delete)
        self.pb_info.clicked.connect(Form.info)
        self.pb_exit.clicked.connect(Form.close)
        self.pb_clear_all.clicked.connect(Form.clear_all)
        self.pb_start.clicked.connect(Form.start)
        self.listWidget.clicked['QModelIndex'].connect(Form.list_clicked)
        self.listWidget.currentRowChanged['int'].connect(Form.list_row_changed)
        self.listWidget.itemClicked['QListWidgetItem*'].connect(Form.list_item_clicked)
        self.listWidget.currentTextChanged['QString'].connect(Form.list_text_changed)
        self.pb_clear_all.clicked.connect(self.listWidget.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "listWidget 控件练习"))
        self.pb_start.setText(_translate("Form", "初始化"))
        self.pb_add.setText(_translate("Form", "增加一个项目"))
        self.pb_del.setText(_translate("Form", "删除一个项目"))
        self.pb_clear_all.setText(_translate("Form", "清空所有项目"))
        self.pb_info.setText(_translate("Form", "当前项目信息"))
        self.pb_exit.setText(_translate("Form", "关闭本窗口"))
        self.pb_exit.setShortcut(_translate("Form", "Esc"))
        self.tb_info.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">info</p></body></html>"))
        self.label.setText(_translate("Form", "listWidget.clicked() 显示的信息："))
        self.label_2.setText(_translate("Form", "当前动作显示信息:"))
        self.label_3.setText(_translate("Form", "list_item_clicked(self,*QListWidgetItem) 显示信息:"))

